module.exports={
    User:require("./User"),
    Admin:require("./Admin"),
    Otp:require("./Otp"),
    Likes:require("./Likes"),
    Posts:require("./Posts"),
    Comments:require("./Comments"),
    Category:require("./Category"),
    AccessRole:require("./AccessRole"),
    Park:require("./Park"),
    CMS:require("./Cms")
};